### ISSUE TITLE
ArrayIndexOutOfBoundsException using getCookies

### ISSUE THREAD

**Issue by davebassan** [MagenTys/cinnamon#7]
See below email from Photobox regarding ArrayIndexOutOfBoundsException using getCookies:

_"Hello guys, I am Automation Engineer on PhotoBox project.
We are using the cinnamon  framework for automation tests and currently faced with one issue.
Let me explain what I mean.
Issue related with method “getCookies()” in the package “io.magentys.cinnamon.webdriver”.
When you have cookie with empty value the exception are raised in line  
The stack trace on the exception is:
 
java.lang.ArrayIndexOutOfBoundsException: 1
at io.magentys.cinnamon.webdriver.CinnamonWebDriverOptions.getCookies(CinnamonWebDriverOptions.java:69)
  at io.magentys.cinnamon.webdriver.CinnamonWebDriverOptions.getCookieNamed(CinnamonWebDriverOptions.java:78)
  at com.photobox.support.SmashSession.getSessionCodeFromCookie(SmashSession.java:25)
  at com.photobox.stepdefs.registration.RegistrationStepDefs.iShouldSeeTheCheckboxStatusInTheBackoffice(RegistrationStepDefs.java:117)
  at ✽.Then I should see the checkbox "News" "ticked" in the backoffice(D:/WorkSpace/PhotoBox/sc-test-automation/sc-acceptance-tests/src/test/resources/features/signInAndRegistration/newsletter_opt_in.feature:12)
[INFO  - 2016-12-20T10:33:22.432Z] ShutdownReqHand - _handle - About to shutdown
 
I would like to ask you guys have a look to this issue, and try to fix it, as it is a cause of failing our test scenarios"_

**Comment by MagenTysHamo** [comment]
Are they paying?

On 4 Jan 2017 7:17 PM, "davebassan" <notifications@github.com> wrote:

See below email from Photobox regarding ArrayIndexOutOfBoundsException
using getCookies:

_"Hello guys, I am Automation Engineer on PhotoBox project.
We are using the cinnamon framework for automation tests and currently
faced with one issue.
Let me explain what I mean.
Issue related with method “getCookies()” in the package
“io.magentys.cinnamon.webdriver”.
When you have cookie with empty value the exception are raised in line
The stack trace on the exception is:

java.lang.ArrayIndexOutOfBoundsException: 1
at io.magentys.cinnamon.webdriver.CinnamonWebDriverOptions.getCookies(
CinnamonWebDriverOptions.java:69)
at io.magentys.cinnamon.webdriver.CinnamonWebDriverOptions.getCookieNamed(
CinnamonWebDriverOptions.java:78)
at com.photobox.support.SmashSession.getSessionCodeFromCookie(
SmashSession.java:25)
at com.photobox.stepdefs.registration.RegistrationStepDefs.
iShouldSeeTheCheckboxStatusInTheBackoffice(RegistrationStepDefs.java:117)
at ✽.Then I should see the checkbox "News" "ticked" in the
backoffice(D:/WorkSpace/PhotoBox/sc-test-automation/
sc-acceptance-tests/src/test/resources/features/signInAndRegistration/
newsletter_opt_in.feature:12)
[INFO - 2016-12-20T10:33:22.432Z] ShutdownReqHand - _handle - About to
shutdown

I would like to ask you guys have a look to this issue, and try to fix it,
as it is a cause of failing our test scenarios"_

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MagenTys/cinnamon/issues/7>, or mute the thread
